### PR TITLE
Update settings.py

### PR DESCRIPTION
**Pull request by guhur**
Move environment variables in the .env, loaded by Docker

### CODE REVIEW

**Comment by sebsheep** [comment]
I'm not very comfortable with "by default values". If a value is not defined in the environment variables, the server should not start. So I'd change all the `environ.get(key, default)` method to `environ[key]` which will crash if the key is not present in the environ.

I'd also add the `.env` file to the PR (I think we can see later how to manage a .env.prod / .env.dev distinction)

**Comment by guhur** [comment]
I updated the .env in the PR https://github.com/MieuxVoter/mvapi/pull/15

**Comment by sebsheep** [comment]
also add the .env? Otherwise LGTM

**Comment by sebsheep** [comment]
> I updated the .env in the PR #15  

Missed this comment.
Ok so I merge this one THEN #15

**Pull request merged**
